services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    volumes:
      - ./data:/data
    env_file:
      - .env
    environment:
      DATABASE_URL: /data/db/errant_fox.db
      PREVIEWS_DIR: /data/previews
      AVATARS_DIR: /data/avatars

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
