# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: clapshot.proto, common.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from datetime import datetime
from typing import (
    Dict,
    List,
    Optional,
)

import betterproto


class UserMessageType(betterproto.Enum):
    OK = 0
    ERROR = 1
    PROGRESS = 2
    MEDIA_FILE_UPDATED = 3
    MEDIA_FILE_ADDED = 4


class ScriptCallLang(betterproto.Enum):
    JAVASCRIPT = 0


@dataclass(eq=False, repr=False)
class Empty(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class MediaFile(betterproto.Message):
    id: str = betterproto.string_field(1)
    title: Optional[str] = betterproto.string_field(2, optional=True, group="_title")
    user_id: str = betterproto.string_field(3)
    media_type: str = betterproto.string_field(4)
    duration: Optional["MediaFileDuration"] = betterproto.message_field(
        5, optional=True, group="_duration"
    )
    added_time: Optional[datetime] = betterproto.message_field(
        6, optional=True, group="_added_time"
    )
    preview_data: Optional["MediaFilePreviewData"] = betterproto.message_field(
        7, optional=True, group="_preview_data"
    )
    processing_metadata: Optional["MediaFileProcessingMetadata"] = (
        betterproto.message_field(8, optional=True, group="_processing_metadata")
    )
    subtitles: List["Subtitle"] = betterproto.message_field(20)
    default_subtitle_id: Optional[str] = betterproto.string_field(
        21, optional=True, group="_default_subtitle_id"
    )
    playback_url: Optional[str] = betterproto.string_field(
        100, optional=True, group="_playback_url"
    )
    orig_url: Optional[str] = betterproto.string_field(
        101, optional=True, group="_orig_url"
    )


@dataclass(eq=False, repr=False)
class MediaFileDuration(betterproto.Message):
    duration: float = betterproto.double_field(1)
    total_frames: int = betterproto.int64_field(2)
    fps: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class MediaFileProcessingMetadata(betterproto.Message):
    recompression_done: Optional[datetime] = betterproto.message_field(
        2, optional=True, group="_recompression_done"
    )
    thumbs_done: Optional[datetime] = betterproto.message_field(
        3, optional=True, group="_thumbs_done"
    )
    orig_filename: str = betterproto.string_field(102)
    ffprobe_metadata_all: Optional[str] = betterproto.string_field(
        103, optional=True, group="_ffprobe_metadata_all"
    )


@dataclass(eq=False, repr=False)
class MediaFilePreviewData(betterproto.Message):
    thumb_url: Optional[str] = betterproto.string_field(
        1, optional=True, group="_thumb_url"
    )
    thumb_sheet: Optional["MediaFilePreviewDataThumbSheet"] = betterproto.message_field(
        2, optional=True, group="_thumb_sheet"
    )


@dataclass(eq=False, repr=False)
class MediaFilePreviewDataThumbSheet(betterproto.Message):
    url: str = betterproto.string_field(1)
    rows: int = betterproto.uint32_field(2)
    cols: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class Subtitle(betterproto.Message):
    id: str = betterproto.string_field(1)
    media_file_id: str = betterproto.string_field(2)
    title: str = betterproto.string_field(3)
    language_code: str = betterproto.string_field(4)
    orig_filename: str = betterproto.string_field(5)
    time_offset: float = betterproto.float_field(6)
    orig_url: str = betterproto.string_field(7)
    playback_url: str = betterproto.string_field(8)
    added_time: Optional[datetime] = betterproto.message_field(
        20, optional=True, group="_added_time"
    )


@dataclass(eq=False, repr=False)
class Comment(betterproto.Message):
    id: str = betterproto.string_field(1)
    media_file_id: str = betterproto.string_field(2)
    user_id: Optional[str] = betterproto.string_field(
        3, optional=True, group="_user_id"
    )
    username_ifnull: str = betterproto.string_field(4)
    comment: str = betterproto.string_field(5)
    timecode: Optional[str] = betterproto.string_field(
        6, optional=True, group="_timecode"
    )
    parent_id: Optional[str] = betterproto.string_field(
        7, optional=True, group="_parent_id"
    )
    drawing: Optional[str] = betterproto.string_field(
        12, optional=True, group="_drawing"
    )
    subtitle_id: Optional[str] = betterproto.string_field(
        20, optional=True, group="_subtitle_id"
    )
    subtitle_filename_ifnull: Optional[str] = betterproto.string_field(
        21, optional=True, group="_subtitle_filename_ifnull"
    )
    created: Optional[datetime] = betterproto.message_field(
        100, optional=True, group="_created"
    )
    edited: Optional[datetime] = betterproto.message_field(
        101, optional=True, group="_edited"
    )


@dataclass(eq=False, repr=False)
class UserMessage(betterproto.Message):
    id: Optional[str] = betterproto.string_field(1, optional=True, group="_id")
    user_id: Optional[str] = betterproto.string_field(
        2, optional=True, group="_user_id"
    )
    created: Optional[datetime] = betterproto.message_field(
        3, optional=True, group="_created"
    )
    seen: bool = betterproto.bool_field(4)
    type: "UserMessageType" = betterproto.enum_field(5)
    refs: "UserMessageRefs" = betterproto.message_field(6)
    message: str = betterproto.string_field(7)
    details: Optional[str] = betterproto.string_field(
        8, optional=True, group="_details"
    )
    progress: Optional[float] = betterproto.float_field(
        9, optional=True, group="_progress"
    )


@dataclass(eq=False, repr=False)
class UserMessageRefs(betterproto.Message):
    media_file_id: Optional[str] = betterproto.string_field(
        1, optional=True, group="_media_file_id"
    )
    comment_id: Optional[str] = betterproto.string_field(
        2, optional=True, group="_comment_id"
    )
    subtitle_id: Optional[str] = betterproto.string_field(
        3, optional=True, group="_subtitle_id"
    )


@dataclass(eq=False, repr=False)
class PageItem(betterproto.Message):
    html: str = betterproto.string_field(1, group="item")
    folder_listing: "PageItemFolderListing" = betterproto.message_field(2, group="item")


@dataclass(eq=False, repr=False)
class PageItemFolderListing(betterproto.Message):
    items: List["PageItemFolderListingItem"] = betterproto.message_field(1)
    popup_actions: List[str] = betterproto.string_field(2)
    listing_data: Dict[str, str] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    allow_reordering: bool = betterproto.bool_field(10)
    allow_upload: bool = betterproto.bool_field(11)
    media_file_added_action: Optional[str] = betterproto.string_field(
        12, optional=True, group="_media_file_added_action"
    )


@dataclass(eq=False, repr=False)
class PageItemFolderListingFolder(betterproto.Message):
    id: str = betterproto.string_field(1)
    title: str = betterproto.string_field(2)
    preview_items: List["PageItemFolderListingItem"] = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class PageItemFolderListingItem(betterproto.Message):
    folder: "PageItemFolderListingFolder" = betterproto.message_field(1, group="item")
    media_file: "MediaFile" = betterproto.message_field(2, group="item")
    vis: Optional["PageItemFolderListingItemVisualization"] = betterproto.message_field(
        100, optional=True, group="_vis"
    )
    open_action: Optional["ScriptCall"] = betterproto.message_field(
        110, optional=True, group="_open_action"
    )
    popup_actions: List[str] = betterproto.string_field(120)


@dataclass(eq=False, repr=False)
class PageItemFolderListingItemVisualization(betterproto.Message):
    base_color: Optional["Color"] = betterproto.message_field(
        1, optional=True, group="_base_color"
    )
    icon: Optional["Icon"] = betterproto.message_field(2, optional=True, group="_icon")


@dataclass(eq=False, repr=False)
class FolderItemId(betterproto.Message):
    folder_id: str = betterproto.string_field(1, group="item")
    media_file_id: str = betterproto.string_field(2, group="item")


@dataclass(eq=False, repr=False)
class ActionUiProps(betterproto.Message):
    label: Optional[str] = betterproto.string_field(1, optional=True, group="_label")
    icon: Optional["Icon"] = betterproto.message_field(2, optional=True, group="_icon")
    key_shortcut: Optional[str] = betterproto.string_field(
        3, optional=True, group="_key_shortcut"
    )
    natural_desc: Optional[str] = betterproto.string_field(
        4, optional=True, group="_natural_desc"
    )
    text_color: Optional["Color"] = betterproto.message_field(
        5, optional=True, group="_text_color"
    )


@dataclass(eq=False, repr=False)
class ActionDef(betterproto.Message):
    ui_props: Optional["ActionUiProps"] = betterproto.message_field(
        1, optional=True, group="_ui_props"
    )
    action: Optional["ScriptCall"] = betterproto.message_field(
        2, optional=True, group="_action"
    )


@dataclass(eq=False, repr=False)
class UserInfo(betterproto.Message):
    id: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class Color(betterproto.Message):
    r: int = betterproto.uint32_field(1)
    g: int = betterproto.uint32_field(2)
    b: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class Icon(betterproto.Message):
    fa_class: "IconFaClass" = betterproto.message_field(1, group="src")
    img_url: str = betterproto.string_field(2, group="src")
    size: Optional[float] = betterproto.float_field(3, optional=True, group="_size")


@dataclass(eq=False, repr=False)
class IconFaClass(betterproto.Message):
    classes: str = betterproto.string_field(1)
    color: Optional["Color"] = betterproto.message_field(
        2, optional=True, group="_color"
    )


@dataclass(eq=False, repr=False)
class ScriptCall(betterproto.Message):
    code: str = betterproto.string_field(1)
    lang: "ScriptCallLang" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class HemaParticipant(betterproto.Message):
    id: int = betterproto.int32_field(1)
    name: str = betterproto.string_field(2)
    club: Optional[str] = betterproto.string_field(3, optional=True, group="_club")


@dataclass(eq=False, repr=False)
class HemaBout(betterproto.Message):
    id: int = betterproto.int32_field(1)
    video_hash: str = betterproto.string_field(2)
    start_time: float = betterproto.float_field(3)
    end_time: float = betterproto.float_field(4)
    participant_a_id: Optional[int] = betterproto.int32_field(
        5, optional=True, group="_participant_a_id"
    )
    participant_b_id: Optional[int] = betterproto.int32_field(
        6, optional=True, group="_participant_b_id"
    )
    score_a: Optional[int] = betterproto.int32_field(7, optional=True, group="_score_a")
    score_b: Optional[int] = betterproto.int32_field(8, optional=True, group="_score_b")
    notes: Optional[str] = betterproto.string_field(9, optional=True, group="_notes")
