services:
  backend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.backend
    restart: unless-stopped
    volumes:
      - ../data:/data
    env_file:
      - ../.env
    environment:
      DATABASE_URL: /data/db/errant_fox.db
      PREVIEWS_DIR: /data/previews
      AVATARS_DIR: /data/avatars
      SQLITE_JOURNAL_MODE: DELETE
    networks:
      - default
      - proxy

  frontend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - default
      - proxy
    labels:
      - traefik.docker.network=proxy
      - traefik.enable=true
      - traefik.http.routers.errantfox.entrypoints=websecure
      - traefik.http.routers.errantfox.rule=Host(`errantfox.aat-terra.ru`)
      - traefik.http.routers.errantfox.tls.certresolver=le-resolver
      - traefik.http.services.errantfox.loadbalancer.server.port=80

networks:
  proxy:
    external: true
