# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: database.proto, organizer.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from datetime import datetime
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

from ... import clapshot as __clapshot__

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class DatabaseDatabaseType(betterproto.Enum):
    SQLITE = 0


class AuthzUserActionRequestOtherOpOp(betterproto.Enum):
    LOGIN = 0
    VIEW_HOME = 1
    UPLOAD_MEDIA_FILE = 2
    JOIN_COLLAB_SESSION = 10


class AuthzUserActionRequestMediaFileOpOp(betterproto.Enum):
    VIEW = 0
    RENAME = 1
    DELETE = 2
    COMMENT = 3
    EDIT = 4


class AuthzUserActionRequestCommentOpOp(betterproto.Enum):
    EDIT = 0
    DELETE = 1


@dataclass(eq=False, repr=False)
class DbGetMediaFilesRequest(betterproto.Message):
    paging: Optional["DbPaging"] = betterproto.message_field(
        1, optional=True, group="_paging"
    )
    all: "__clapshot__.Empty" = betterproto.message_field(10, group="filter")
    ids: "IdList" = betterproto.message_field(11, group="filter")
    user_id: str = betterproto.string_field(12, group="filter")


@dataclass(eq=False, repr=False)
class DbGetCommentsRequest(betterproto.Message):
    paging: Optional["DbPaging"] = betterproto.message_field(
        1, optional=True, group="_paging"
    )
    all: "__clapshot__.Empty" = betterproto.message_field(10, group="filter")
    ids: "IdList" = betterproto.message_field(11, group="filter")
    user_id: str = betterproto.string_field(12, group="filter")
    media_file_id: str = betterproto.string_field(13, group="filter")


@dataclass(eq=False, repr=False)
class DbGetUserMessagesRequest(betterproto.Message):
    paging: Optional["DbPaging"] = betterproto.message_field(
        1, optional=True, group="_paging"
    )
    all: "__clapshot__.Empty" = betterproto.message_field(10, group="filter")
    ids: "IdList" = betterproto.message_field(11, group="filter")
    user_id: str = betterproto.string_field(12, group="filter")
    media_file_id: str = betterproto.string_field(13, group="filter")
    comment_id: str = betterproto.string_field(14, group="filter")


@dataclass(eq=False, repr=False)
class DbGetHemaParticipantsRequest(betterproto.Message):
    paging: Optional["DbPaging"] = betterproto.message_field(
        1, optional=True, group="_paging"
    )
    all: "__clapshot__.Empty" = betterproto.message_field(10, group="filter")
    ids: "IdList" = betterproto.message_field(11, group="filter")


@dataclass(eq=False, repr=False)
class DbGetHemaBoutsRequest(betterproto.Message):
    paging: Optional["DbPaging"] = betterproto.message_field(
        1, optional=True, group="_paging"
    )
    all: "__clapshot__.Empty" = betterproto.message_field(10, group="filter")
    media_file_id: str = betterproto.string_field(11, group="filter")


@dataclass(eq=False, repr=False)
class DbUpsertRequest(betterproto.Message):
    """
    Add or replace objects in the database. If an ID is not specified, a new
    object will be created, otherwise the existing object will be replaced.
    """

    media_files: List["__clapshot__.MediaFile"] = betterproto.message_field(1)
    subtitles: List["__clapshot__.Subtitle"] = betterproto.message_field(2)
    comments: List["__clapshot__.Comment"] = betterproto.message_field(3)
    user_messages: List["__clapshot__.UserMessage"] = betterproto.message_field(4)
    hema_participants: List["__clapshot__.HemaParticipant"] = betterproto.message_field(
        5
    )
    hema_bouts: List["__clapshot__.HemaBout"] = betterproto.message_field(6)


@dataclass(eq=False, repr=False)
class DbUpsertResponse(betterproto.Message):
    media_files: List["__clapshot__.MediaFile"] = betterproto.message_field(1)
    """These will have IDs, creation timestamps, etc. filled in."""

    subtitles: List["__clapshot__.Subtitle"] = betterproto.message_field(2)
    comments: List["__clapshot__.Comment"] = betterproto.message_field(3)
    user_messages: List["__clapshot__.UserMessage"] = betterproto.message_field(4)
    hema_participants: List["__clapshot__.HemaParticipant"] = betterproto.message_field(
        5
    )
    hema_bouts: List["__clapshot__.HemaBout"] = betterproto.message_field(6)


@dataclass(eq=False, repr=False)
class DbDeleteRequest(betterproto.Message):
    media_file_ids: List[str] = betterproto.string_field(1)
    subtitle_ids: List[str] = betterproto.string_field(2)
    comment_ids: List[str] = betterproto.string_field(3)
    user_message_ids: List[str] = betterproto.string_field(4)
    hema_participant_ids: List[int] = betterproto.int32_field(5)
    hema_bout_ids: List[int] = betterproto.int32_field(6)


@dataclass(eq=False, repr=False)
class DbDeleteResponse(betterproto.Message):
    media_files_deleted: int = betterproto.uint32_field(1)
    subtitles_deleted: int = betterproto.uint32_field(2)
    comments_deleted: int = betterproto.uint32_field(3)
    user_messages_deleted: int = betterproto.uint32_field(4)
    hema_participants_deleted: int = betterproto.uint32_field(5)
    hema_bouts_deleted: int = betterproto.uint32_field(6)


@dataclass(eq=False, repr=False)
class DbPaging(betterproto.Message):
    page_num: int = betterproto.uint32_field(1)
    page_size: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class IdList(betterproto.Message):
    ids: List[str] = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class DbMediaFileList(betterproto.Message):
    items: List["__clapshot__.MediaFile"] = betterproto.message_field(1)
    paging: Optional["DbPaging"] = betterproto.message_field(
        2, optional=True, group="_paging"
    )


@dataclass(eq=False, repr=False)
class DbSubtitleList(betterproto.Message):
    items: List["__clapshot__.Subtitle"] = betterproto.message_field(1)
    paging: Optional["DbPaging"] = betterproto.message_field(
        2, optional=True, group="_paging"
    )


@dataclass(eq=False, repr=False)
class DbCommentList(betterproto.Message):
    items: List["__clapshot__.Comment"] = betterproto.message_field(1)
    paging: Optional["DbPaging"] = betterproto.message_field(
        2, optional=True, group="_paging"
    )


@dataclass(eq=False, repr=False)
class DbUserMessageList(betterproto.Message):
    items: List["__clapshot__.UserMessage"] = betterproto.message_field(1)
    paging: Optional["DbPaging"] = betterproto.message_field(
        2, optional=True, group="_paging"
    )


@dataclass(eq=False, repr=False)
class DbHemaParticipantList(betterproto.Message):
    items: List["__clapshot__.HemaParticipant"] = betterproto.message_field(1)
    paging: Optional["DbPaging"] = betterproto.message_field(
        2, optional=True, group="_paging"
    )


@dataclass(eq=False, repr=False)
class DbHemaBoutList(betterproto.Message):
    items: List["__clapshot__.HemaBout"] = betterproto.message_field(1)
    paging: Optional["DbPaging"] = betterproto.message_field(
        2, optional=True, group="_paging"
    )


@dataclass(eq=False, repr=False)
class Database(betterproto.Message):
    type: "DatabaseDatabaseType" = betterproto.enum_field(1)
    endpoint: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class ServerInfo(betterproto.Message):
    version: "SemanticVersionNumber" = betterproto.message_field(1)
    storage: "ServerInfoStorage" = betterproto.message_field(3)
    url_base: str = betterproto.string_field(4)
    db: "Database" = betterproto.message_field(5)
    backchannel: "ServerInfoGrpcEndpoint" = betterproto.message_field(6)


@dataclass(eq=False, repr=False)
class ServerInfoStorage(betterproto.Message):
    local_fs: "ServerInfoStorageLocalFilesystem" = betterproto.message_field(
        1, group="storage"
    )


@dataclass(eq=False, repr=False)
class ServerInfoStorageLocalFilesystem(betterproto.Message):
    base_dir: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ServerInfoGrpcEndpoint(betterproto.Message):
    unix: "ServerInfoGrpcEndpointUnix" = betterproto.message_field(1, group="endpoint")
    tcp: "ServerInfoGrpcEndpointTcp" = betterproto.message_field(2, group="endpoint")


@dataclass(eq=False, repr=False)
class ServerInfoGrpcEndpointUnix(betterproto.Message):
    path: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ServerInfoGrpcEndpointTcp(betterproto.Message):
    host: str = betterproto.string_field(1)
    port: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class OrganizerInfo(betterproto.Message):
    version: "SemanticVersionNumber" = betterproto.message_field(1)
    name: str = betterproto.string_field(2)
    description: str = betterproto.string_field(3)
    hard_dependencies: List["OrganizerDependency"] = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class OrganizerDependency(betterproto.Message):
    name: str = betterproto.string_field(1)
    min_ver: "SemanticVersionNumber" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class SemanticVersionNumber(betterproto.Message):
    major: int = betterproto.uint64_field(1)
    minor: int = betterproto.uint64_field(2)
    patch: int = betterproto.uint64_field(3)


@dataclass(eq=False, repr=False)
class Migration(betterproto.Message):
    uuid: str = betterproto.string_field(1)
    version: str = betterproto.string_field(2)
    dependencies: List["MigrationDependency"] = betterproto.message_field(3)
    description: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class MigrationDependency(betterproto.Message):
    name: str = betterproto.string_field(1)
    min_ver: Optional[str] = betterproto.string_field(
        2, optional=True, group="_min_ver"
    )
    max_ver: Optional[str] = betterproto.string_field(
        3, optional=True, group="_max_ver"
    )


@dataclass(eq=False, repr=False)
class CheckMigrationsRequest(betterproto.Message):
    db: "Database" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class CheckMigrationsResponse(betterproto.Message):
    name: str = betterproto.string_field(1)
    current_schema_ver: str = betterproto.string_field(2)
    pending_migrations: List["Migration"] = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class ApplyMigrationRequest(betterproto.Message):
    db: "Database" = betterproto.message_field(1)
    uuid: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class ApplyMigrationResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class AfterMigrationsRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class UserSessionData(betterproto.Message):
    sid: str = betterproto.string_field(1)
    user: "__clapshot__.UserInfo" = betterproto.message_field(2)
    is_admin: bool = betterproto.bool_field(3)
    cookies: Dict[str, str] = betterproto.map_field(
        4, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    http_headers: Dict[str, str] = betterproto.map_field(
        5, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class OnStartUserSessionRequest(betterproto.Message):
    ses: "UserSessionData" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class OnStartUserSessionResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class NavigatePageRequest(betterproto.Message):
    ses: "UserSessionData" = betterproto.message_field(1)
    page_id: Optional[str] = betterproto.string_field(
        2, optional=True, group="_page_id"
    )


@dataclass(eq=False, repr=False)
class CmdFromClientRequest(betterproto.Message):
    ses: "UserSessionData" = betterproto.message_field(1)
    cmd: str = betterproto.string_field(2)
    args: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class MoveToFolderRequest(betterproto.Message):
    ses: "UserSessionData" = betterproto.message_field(1)
    ids: List["__clapshot__.FolderItemId"] = betterproto.message_field(2)
    dst_folder_id: str = betterproto.string_field(3)
    listing_data: Dict[str, str] = betterproto.map_field(
        4, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class ReorderItemsRequest(betterproto.Message):
    ses: "UserSessionData" = betterproto.message_field(1)
    ids: List["__clapshot__.FolderItemId"] = betterproto.message_field(2)
    listing_data: Dict[str, str] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class OnMediaFileIngestedRequest(betterproto.Message):
    user_id: str = betterproto.string_field(1)
    media_file_id: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class AuthzUserActionRequest(betterproto.Message):
    ses: "UserSessionData" = betterproto.message_field(1)
    other_op: "AuthzUserActionRequestOtherOp" = betterproto.message_field(8, group="op")
    media_file_op: "AuthzUserActionRequestMediaFileOp" = betterproto.message_field(
        9, group="op"
    )
    comment_op: "AuthzUserActionRequestCommentOp" = betterproto.message_field(
        10, group="op"
    )


@dataclass(eq=False, repr=False)
class AuthzUserActionRequestOtherOp(betterproto.Message):
    op: "AuthzUserActionRequestOtherOpOp" = betterproto.enum_field(1)
    subject: Optional[str] = betterproto.string_field(
        2, optional=True, group="_subject"
    )


@dataclass(eq=False, repr=False)
class AuthzUserActionRequestMediaFileOp(betterproto.Message):
    media_file: "__clapshot__.MediaFile" = betterproto.message_field(1)
    op: "AuthzUserActionRequestMediaFileOpOp" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class AuthzUserActionRequestCommentOp(betterproto.Message):
    comment: "__clapshot__.Comment" = betterproto.message_field(1)
    op: "AuthzUserActionRequestCommentOpOp" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class AuthzResponse(betterproto.Message):
    is_authorized: Optional[bool] = betterproto.bool_field(
        1, optional=True, group="_is_authorized"
    )
    message: Optional[str] = betterproto.string_field(
        2, optional=True, group="_message"
    )
    details: Optional[str] = betterproto.string_field(
        3, optional=True, group="_details"
    )


@dataclass(eq=False, repr=False)
class ListTestsResponse(betterproto.Message):
    test_names: List[str] = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class RunTestRequest(betterproto.Message):
    test_name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class RunTestResponse(betterproto.Message):
    output: str = betterproto.string_field(1)
    error: Optional[str] = betterproto.string_field(2, optional=True, group="_error")


@dataclass(eq=False, repr=False)
class ClientShowPageRequest(betterproto.Message):
    sid: str = betterproto.string_field(1)
    page_items: List["__clapshot__.PageItem"] = betterproto.message_field(2)
    page_id: Optional[str] = betterproto.string_field(
        3, optional=True, group="_page_id"
    )
    page_title: Optional[str] = betterproto.string_field(
        4, optional=True, group="_page_title"
    )


@dataclass(eq=False, repr=False)
class ClientShowUserMessageRequest(betterproto.Message):
    msg: "__clapshot__.UserMessage" = betterproto.message_field(1)
    sid: str = betterproto.string_field(100, group="recipient")
    user_temp: str = betterproto.string_field(101, group="recipient")
    user_persist: str = betterproto.string_field(102, group="recipient")
    media_file_id: str = betterproto.string_field(103, group="recipient")
    collab_session: str = betterproto.string_field(104, group="recipient")


@dataclass(eq=False, repr=False)
class ClientDefineActionsRequest(betterproto.Message):
    sid: str = betterproto.string_field(1)
    actions: Dict[str, "__clapshot__.ActionDef"] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )


@dataclass(eq=False, repr=False)
class ClientOpenMediaFileRequest(betterproto.Message):
    """Tell client of session `sid` to open media file `id` in the player"""

    sid: str = betterproto.string_field(1)
    id: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class ClientSetCookiesRequest(betterproto.Message):
    sid: str = betterproto.string_field(1)
    cookies: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    expire_time: Optional[datetime] = betterproto.message_field(
        3, optional=True, group="_expire_time"
    )


@dataclass(eq=False, repr=False)
class DeleteMediaFileRequest(betterproto.Message):
    id: str = betterproto.string_field(1)


class OrganizerOutboundStub(betterproto.ServiceStub):
    async def handshake(
        self,
        organizer_info: "OrganizerInfo",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__clapshot__.Empty":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerOutbound/handshake",
            organizer_info,
            __clapshot__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def client_define_actions(
        self,
        client_define_actions_request: "ClientDefineActionsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__clapshot__.Empty":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerOutbound/client_define_actions",
            client_define_actions_request,
            __clapshot__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def client_show_page(
        self,
        client_show_page_request: "ClientShowPageRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__clapshot__.Empty":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerOutbound/client_show_page",
            client_show_page_request,
            __clapshot__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def client_show_user_message(
        self,
        client_show_user_message_request: "ClientShowUserMessageRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__clapshot__.Empty":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerOutbound/client_show_user_message",
            client_show_user_message_request,
            __clapshot__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def client_open_media_file(
        self,
        client_open_media_file_request: "ClientOpenMediaFileRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__clapshot__.Empty":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerOutbound/client_open_media_file",
            client_open_media_file_request,
            __clapshot__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def client_set_cookies(
        self,
        client_set_cookies_request: "ClientSetCookiesRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__clapshot__.Empty":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerOutbound/client_set_cookies",
            client_set_cookies_request,
            __clapshot__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def delete_media_file(
        self,
        delete_media_file_request: "DeleteMediaFileRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__clapshot__.Empty":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerOutbound/delete_media_file",
            delete_media_file_request,
            __clapshot__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def db_get_media_files(
        self,
        db_get_media_files_request: "DbGetMediaFilesRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DbMediaFileList":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerOutbound/DbGetMediaFiles",
            db_get_media_files_request,
            DbMediaFileList,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def db_get_comments(
        self,
        db_get_comments_request: "DbGetCommentsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DbCommentList":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerOutbound/DbGetComments",
            db_get_comments_request,
            DbCommentList,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def db_get_user_messages(
        self,
        db_get_user_messages_request: "DbGetUserMessagesRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DbUserMessageList":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerOutbound/DbGetUserMessages",
            db_get_user_messages_request,
            DbUserMessageList,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def db_get_hema_participants(
        self,
        db_get_hema_participants_request: "DbGetHemaParticipantsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DbHemaParticipantList":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerOutbound/DbGetHemaParticipants",
            db_get_hema_participants_request,
            DbHemaParticipantList,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def db_get_hema_bouts(
        self,
        db_get_hema_bouts_request: "DbGetHemaBoutsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DbHemaBoutList":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerOutbound/DbGetHemaBouts",
            db_get_hema_bouts_request,
            DbHemaBoutList,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def db_upsert(
        self,
        db_upsert_request: "DbUpsertRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DbUpsertResponse":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerOutbound/DbUpsert",
            db_upsert_request,
            DbUpsertResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def db_delete(
        self,
        db_delete_request: "DbDeleteRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DbDeleteResponse":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerOutbound/DbDelete",
            db_delete_request,
            DbDeleteResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class OrganizerInboundStub(betterproto.ServiceStub):
    async def check_migrations(
        self,
        check_migrations_request: "CheckMigrationsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "CheckMigrationsResponse":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerInbound/check_migrations",
            check_migrations_request,
            CheckMigrationsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def apply_migration(
        self,
        apply_migration_request: "ApplyMigrationRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ApplyMigrationResponse":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerInbound/apply_migration",
            apply_migration_request,
            ApplyMigrationResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def handshake(
        self,
        server_info: "ServerInfo",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__clapshot__.Empty":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerInbound/handshake",
            server_info,
            __clapshot__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def on_start_user_session(
        self,
        on_start_user_session_request: "OnStartUserSessionRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "OnStartUserSessionResponse":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerInbound/on_start_user_session",
            on_start_user_session_request,
            OnStartUserSessionResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def navigate_page(
        self,
        navigate_page_request: "NavigatePageRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ClientShowPageRequest":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerInbound/navigate_page",
            navigate_page_request,
            ClientShowPageRequest,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def authz_user_action(
        self,
        authz_user_action_request: "AuthzUserActionRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "AuthzResponse":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerInbound/authz_user_action",
            authz_user_action_request,
            AuthzResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def cmd_from_client(
        self,
        cmd_from_client_request: "CmdFromClientRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__clapshot__.Empty":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerInbound/cmd_from_client",
            cmd_from_client_request,
            __clapshot__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def on_media_file_ingested(
        self,
        on_media_file_ingested_request: "OnMediaFileIngestedRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__clapshot__.Empty":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerInbound/on_media_file_ingested",
            on_media_file_ingested_request,
            __clapshot__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def move_to_folder(
        self,
        move_to_folder_request: "MoveToFolderRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__clapshot__.Empty":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerInbound/move_to_folder",
            move_to_folder_request,
            __clapshot__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def reorder_items(
        self,
        reorder_items_request: "ReorderItemsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "__clapshot__.Empty":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerInbound/reorder_items",
            reorder_items_request,
            __clapshot__.Empty,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_tests(
        self,
        clapshot_empty: "__clapshot__.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ListTestsResponse":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerInbound/list_tests",
            clapshot_empty,
            ListTestsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def run_test(
        self,
        run_test_request: "RunTestRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "RunTestResponse":
        return await self._unary_unary(
            "/clapshot.organizer.OrganizerInbound/run_test",
            run_test_request,
            RunTestResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class OrganizerOutboundBase(ServiceBase):

    async def handshake(self, organizer_info: "OrganizerInfo") -> "__clapshot__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def client_define_actions(
        self, client_define_actions_request: "ClientDefineActionsRequest"
    ) -> "__clapshot__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def client_show_page(
        self, client_show_page_request: "ClientShowPageRequest"
    ) -> "__clapshot__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def client_show_user_message(
        self, client_show_user_message_request: "ClientShowUserMessageRequest"
    ) -> "__clapshot__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def client_open_media_file(
        self, client_open_media_file_request: "ClientOpenMediaFileRequest"
    ) -> "__clapshot__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def client_set_cookies(
        self, client_set_cookies_request: "ClientSetCookiesRequest"
    ) -> "__clapshot__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def delete_media_file(
        self, delete_media_file_request: "DeleteMediaFileRequest"
    ) -> "__clapshot__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def db_get_media_files(
        self, db_get_media_files_request: "DbGetMediaFilesRequest"
    ) -> "DbMediaFileList":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def db_get_comments(
        self, db_get_comments_request: "DbGetCommentsRequest"
    ) -> "DbCommentList":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def db_get_user_messages(
        self, db_get_user_messages_request: "DbGetUserMessagesRequest"
    ) -> "DbUserMessageList":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def db_get_hema_participants(
        self, db_get_hema_participants_request: "DbGetHemaParticipantsRequest"
    ) -> "DbHemaParticipantList":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def db_get_hema_bouts(
        self, db_get_hema_bouts_request: "DbGetHemaBoutsRequest"
    ) -> "DbHemaBoutList":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def db_upsert(
        self, db_upsert_request: "DbUpsertRequest"
    ) -> "DbUpsertResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def db_delete(
        self, db_delete_request: "DbDeleteRequest"
    ) -> "DbDeleteResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_handshake(
        self, stream: "grpclib.server.Stream[OrganizerInfo, __clapshot__.Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.handshake(request)
        await stream.send_message(response)

    async def __rpc_client_define_actions(
        self,
        stream: "grpclib.server.Stream[ClientDefineActionsRequest, __clapshot__.Empty]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.client_define_actions(request)
        await stream.send_message(response)

    async def __rpc_client_show_page(
        self, stream: "grpclib.server.Stream[ClientShowPageRequest, __clapshot__.Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.client_show_page(request)
        await stream.send_message(response)

    async def __rpc_client_show_user_message(
        self,
        stream: "grpclib.server.Stream[ClientShowUserMessageRequest, __clapshot__.Empty]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.client_show_user_message(request)
        await stream.send_message(response)

    async def __rpc_client_open_media_file(
        self,
        stream: "grpclib.server.Stream[ClientOpenMediaFileRequest, __clapshot__.Empty]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.client_open_media_file(request)
        await stream.send_message(response)

    async def __rpc_client_set_cookies(
        self,
        stream: "grpclib.server.Stream[ClientSetCookiesRequest, __clapshot__.Empty]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.client_set_cookies(request)
        await stream.send_message(response)

    async def __rpc_delete_media_file(
        self,
        stream: "grpclib.server.Stream[DeleteMediaFileRequest, __clapshot__.Empty]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.delete_media_file(request)
        await stream.send_message(response)

    async def __rpc_db_get_media_files(
        self, stream: "grpclib.server.Stream[DbGetMediaFilesRequest, DbMediaFileList]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.db_get_media_files(request)
        await stream.send_message(response)

    async def __rpc_db_get_comments(
        self, stream: "grpclib.server.Stream[DbGetCommentsRequest, DbCommentList]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.db_get_comments(request)
        await stream.send_message(response)

    async def __rpc_db_get_user_messages(
        self,
        stream: "grpclib.server.Stream[DbGetUserMessagesRequest, DbUserMessageList]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.db_get_user_messages(request)
        await stream.send_message(response)

    async def __rpc_db_get_hema_participants(
        self,
        stream: "grpclib.server.Stream[DbGetHemaParticipantsRequest, DbHemaParticipantList]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.db_get_hema_participants(request)
        await stream.send_message(response)

    async def __rpc_db_get_hema_bouts(
        self, stream: "grpclib.server.Stream[DbGetHemaBoutsRequest, DbHemaBoutList]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.db_get_hema_bouts(request)
        await stream.send_message(response)

    async def __rpc_db_upsert(
        self, stream: "grpclib.server.Stream[DbUpsertRequest, DbUpsertResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.db_upsert(request)
        await stream.send_message(response)

    async def __rpc_db_delete(
        self, stream: "grpclib.server.Stream[DbDeleteRequest, DbDeleteResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.db_delete(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/clapshot.organizer.OrganizerOutbound/handshake": grpclib.const.Handler(
                self.__rpc_handshake,
                grpclib.const.Cardinality.UNARY_UNARY,
                OrganizerInfo,
                __clapshot__.Empty,
            ),
            "/clapshot.organizer.OrganizerOutbound/client_define_actions": grpclib.const.Handler(
                self.__rpc_client_define_actions,
                grpclib.const.Cardinality.UNARY_UNARY,
                ClientDefineActionsRequest,
                __clapshot__.Empty,
            ),
            "/clapshot.organizer.OrganizerOutbound/client_show_page": grpclib.const.Handler(
                self.__rpc_client_show_page,
                grpclib.const.Cardinality.UNARY_UNARY,
                ClientShowPageRequest,
                __clapshot__.Empty,
            ),
            "/clapshot.organizer.OrganizerOutbound/client_show_user_message": grpclib.const.Handler(
                self.__rpc_client_show_user_message,
                grpclib.const.Cardinality.UNARY_UNARY,
                ClientShowUserMessageRequest,
                __clapshot__.Empty,
            ),
            "/clapshot.organizer.OrganizerOutbound/client_open_media_file": grpclib.const.Handler(
                self.__rpc_client_open_media_file,
                grpclib.const.Cardinality.UNARY_UNARY,
                ClientOpenMediaFileRequest,
                __clapshot__.Empty,
            ),
            "/clapshot.organizer.OrganizerOutbound/client_set_cookies": grpclib.const.Handler(
                self.__rpc_client_set_cookies,
                grpclib.const.Cardinality.UNARY_UNARY,
                ClientSetCookiesRequest,
                __clapshot__.Empty,
            ),
            "/clapshot.organizer.OrganizerOutbound/delete_media_file": grpclib.const.Handler(
                self.__rpc_delete_media_file,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeleteMediaFileRequest,
                __clapshot__.Empty,
            ),
            "/clapshot.organizer.OrganizerOutbound/DbGetMediaFiles": grpclib.const.Handler(
                self.__rpc_db_get_media_files,
                grpclib.const.Cardinality.UNARY_UNARY,
                DbGetMediaFilesRequest,
                DbMediaFileList,
            ),
            "/clapshot.organizer.OrganizerOutbound/DbGetComments": grpclib.const.Handler(
                self.__rpc_db_get_comments,
                grpclib.const.Cardinality.UNARY_UNARY,
                DbGetCommentsRequest,
                DbCommentList,
            ),
            "/clapshot.organizer.OrganizerOutbound/DbGetUserMessages": grpclib.const.Handler(
                self.__rpc_db_get_user_messages,
                grpclib.const.Cardinality.UNARY_UNARY,
                DbGetUserMessagesRequest,
                DbUserMessageList,
            ),
            "/clapshot.organizer.OrganizerOutbound/DbGetHemaParticipants": grpclib.const.Handler(
                self.__rpc_db_get_hema_participants,
                grpclib.const.Cardinality.UNARY_UNARY,
                DbGetHemaParticipantsRequest,
                DbHemaParticipantList,
            ),
            "/clapshot.organizer.OrganizerOutbound/DbGetHemaBouts": grpclib.const.Handler(
                self.__rpc_db_get_hema_bouts,
                grpclib.const.Cardinality.UNARY_UNARY,
                DbGetHemaBoutsRequest,
                DbHemaBoutList,
            ),
            "/clapshot.organizer.OrganizerOutbound/DbUpsert": grpclib.const.Handler(
                self.__rpc_db_upsert,
                grpclib.const.Cardinality.UNARY_UNARY,
                DbUpsertRequest,
                DbUpsertResponse,
            ),
            "/clapshot.organizer.OrganizerOutbound/DbDelete": grpclib.const.Handler(
                self.__rpc_db_delete,
                grpclib.const.Cardinality.UNARY_UNARY,
                DbDeleteRequest,
                DbDeleteResponse,
            ),
        }


class OrganizerInboundBase(ServiceBase):

    async def check_migrations(
        self, check_migrations_request: "CheckMigrationsRequest"
    ) -> "CheckMigrationsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def apply_migration(
        self, apply_migration_request: "ApplyMigrationRequest"
    ) -> "ApplyMigrationResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def handshake(self, server_info: "ServerInfo") -> "__clapshot__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def on_start_user_session(
        self, on_start_user_session_request: "OnStartUserSessionRequest"
    ) -> "OnStartUserSessionResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def navigate_page(
        self, navigate_page_request: "NavigatePageRequest"
    ) -> "ClientShowPageRequest":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def authz_user_action(
        self, authz_user_action_request: "AuthzUserActionRequest"
    ) -> "AuthzResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def cmd_from_client(
        self, cmd_from_client_request: "CmdFromClientRequest"
    ) -> "__clapshot__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def on_media_file_ingested(
        self, on_media_file_ingested_request: "OnMediaFileIngestedRequest"
    ) -> "__clapshot__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def move_to_folder(
        self, move_to_folder_request: "MoveToFolderRequest"
    ) -> "__clapshot__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def reorder_items(
        self, reorder_items_request: "ReorderItemsRequest"
    ) -> "__clapshot__.Empty":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_tests(
        self, clapshot_empty: "__clapshot__.Empty"
    ) -> "ListTestsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def run_test(self, run_test_request: "RunTestRequest") -> "RunTestResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_check_migrations(
        self,
        stream: "grpclib.server.Stream[CheckMigrationsRequest, CheckMigrationsResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.check_migrations(request)
        await stream.send_message(response)

    async def __rpc_apply_migration(
        self,
        stream: "grpclib.server.Stream[ApplyMigrationRequest, ApplyMigrationResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.apply_migration(request)
        await stream.send_message(response)

    async def __rpc_handshake(
        self, stream: "grpclib.server.Stream[ServerInfo, __clapshot__.Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.handshake(request)
        await stream.send_message(response)

    async def __rpc_on_start_user_session(
        self,
        stream: "grpclib.server.Stream[OnStartUserSessionRequest, OnStartUserSessionResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.on_start_user_session(request)
        await stream.send_message(response)

    async def __rpc_navigate_page(
        self,
        stream: "grpclib.server.Stream[NavigatePageRequest, ClientShowPageRequest]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.navigate_page(request)
        await stream.send_message(response)

    async def __rpc_authz_user_action(
        self, stream: "grpclib.server.Stream[AuthzUserActionRequest, AuthzResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.authz_user_action(request)
        await stream.send_message(response)

    async def __rpc_cmd_from_client(
        self, stream: "grpclib.server.Stream[CmdFromClientRequest, __clapshot__.Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.cmd_from_client(request)
        await stream.send_message(response)

    async def __rpc_on_media_file_ingested(
        self,
        stream: "grpclib.server.Stream[OnMediaFileIngestedRequest, __clapshot__.Empty]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.on_media_file_ingested(request)
        await stream.send_message(response)

    async def __rpc_move_to_folder(
        self, stream: "grpclib.server.Stream[MoveToFolderRequest, __clapshot__.Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.move_to_folder(request)
        await stream.send_message(response)

    async def __rpc_reorder_items(
        self, stream: "grpclib.server.Stream[ReorderItemsRequest, __clapshot__.Empty]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.reorder_items(request)
        await stream.send_message(response)

    async def __rpc_list_tests(
        self, stream: "grpclib.server.Stream[__clapshot__.Empty, ListTestsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_tests(request)
        await stream.send_message(response)

    async def __rpc_run_test(
        self, stream: "grpclib.server.Stream[RunTestRequest, RunTestResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.run_test(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/clapshot.organizer.OrganizerInbound/check_migrations": grpclib.const.Handler(
                self.__rpc_check_migrations,
                grpclib.const.Cardinality.UNARY_UNARY,
                CheckMigrationsRequest,
                CheckMigrationsResponse,
            ),
            "/clapshot.organizer.OrganizerInbound/apply_migration": grpclib.const.Handler(
                self.__rpc_apply_migration,
                grpclib.const.Cardinality.UNARY_UNARY,
                ApplyMigrationRequest,
                ApplyMigrationResponse,
            ),
            "/clapshot.organizer.OrganizerInbound/handshake": grpclib.const.Handler(
                self.__rpc_handshake,
                grpclib.const.Cardinality.UNARY_UNARY,
                ServerInfo,
                __clapshot__.Empty,
            ),
            "/clapshot.organizer.OrganizerInbound/on_start_user_session": grpclib.const.Handler(
                self.__rpc_on_start_user_session,
                grpclib.const.Cardinality.UNARY_UNARY,
                OnStartUserSessionRequest,
                OnStartUserSessionResponse,
            ),
            "/clapshot.organizer.OrganizerInbound/navigate_page": grpclib.const.Handler(
                self.__rpc_navigate_page,
                grpclib.const.Cardinality.UNARY_UNARY,
                NavigatePageRequest,
                ClientShowPageRequest,
            ),
            "/clapshot.organizer.OrganizerInbound/authz_user_action": grpclib.const.Handler(
                self.__rpc_authz_user_action,
                grpclib.const.Cardinality.UNARY_UNARY,
                AuthzUserActionRequest,
                AuthzResponse,
            ),
            "/clapshot.organizer.OrganizerInbound/cmd_from_client": grpclib.const.Handler(
                self.__rpc_cmd_from_client,
                grpclib.const.Cardinality.UNARY_UNARY,
                CmdFromClientRequest,
                __clapshot__.Empty,
            ),
            "/clapshot.organizer.OrganizerInbound/on_media_file_ingested": grpclib.const.Handler(
                self.__rpc_on_media_file_ingested,
                grpclib.const.Cardinality.UNARY_UNARY,
                OnMediaFileIngestedRequest,
                __clapshot__.Empty,
            ),
            "/clapshot.organizer.OrganizerInbound/move_to_folder": grpclib.const.Handler(
                self.__rpc_move_to_folder,
                grpclib.const.Cardinality.UNARY_UNARY,
                MoveToFolderRequest,
                __clapshot__.Empty,
            ),
            "/clapshot.organizer.OrganizerInbound/reorder_items": grpclib.const.Handler(
                self.__rpc_reorder_items,
                grpclib.const.Cardinality.UNARY_UNARY,
                ReorderItemsRequest,
                __clapshot__.Empty,
            ),
            "/clapshot.organizer.OrganizerInbound/list_tests": grpclib.const.Handler(
                self.__rpc_list_tests,
                grpclib.const.Cardinality.UNARY_UNARY,
                __clapshot__.Empty,
                ListTestsResponse,
            ),
            "/clapshot.organizer.OrganizerInbound/run_test": grpclib.const.Handler(
                self.__rpc_run_test,
                grpclib.const.Cardinality.UNARY_UNARY,
                RunTestRequest,
                RunTestResponse,
            ),
        }
