# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: client.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from datetime import datetime
from typing import (
    Dict,
    List,
    Optional,
)

import betterproto

from ... import clapshot as __clapshot__


@dataclass(eq=False, repr=False)
class ServerToClientCmd(betterproto.Message):
    welcome: "ServerToClientCmdWelcome" = betterproto.message_field(10, group="cmd")
    error: "ServerToClientCmdError" = betterproto.message_field(20, group="cmd")
    show_page: "ServerToClientCmdShowPage" = betterproto.message_field(30, group="cmd")
    define_actions: "ServerToClientCmdDefineActions" = betterproto.message_field(
        40, group="cmd"
    )
    show_messages: "ServerToClientCmdShowMessages" = betterproto.message_field(
        50, group="cmd"
    )
    open_media_file: "ServerToClientCmdOpenMediaFile" = betterproto.message_field(
        60, group="cmd"
    )
    add_comments: "ServerToClientCmdAddComments" = betterproto.message_field(
        70, group="cmd"
    )
    del_comment: "ServerToClientCmdDelComment" = betterproto.message_field(
        80, group="cmd"
    )
    collab_event: "ServerToClientCmdCollabEvent" = betterproto.message_field(
        90, group="cmd"
    )
    set_cookies: "ServerToClientCmdSetCookies" = betterproto.message_field(
        100, group="cmd"
    )
    hema_participants: "ServerToClientCmdHemaParticipants" = betterproto.message_field(
        160, group="cmd"
    )
    hema_media_bouts: "ServerToClientCmdHemaMediaBouts" = betterproto.message_field(
        161, group="cmd"
    )


@dataclass(eq=False, repr=False)
class ServerToClientCmdWelcome(betterproto.Message):
    user: "__clapshot__.UserInfo" = betterproto.message_field(1)
    is_admin: bool = betterproto.bool_field(2)
    server_version: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class ServerToClientCmdError(betterproto.Message):
    msg: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ServerToClientCmdShowPage(betterproto.Message):
    page_items: List["__clapshot__.PageItem"] = betterproto.message_field(1)
    page_id: Optional[str] = betterproto.string_field(
        2, optional=True, group="_page_id"
    )
    page_title: Optional[str] = betterproto.string_field(
        3, optional=True, group="_page_title"
    )


@dataclass(eq=False, repr=False)
class ServerToClientCmdDefineActions(betterproto.Message):
    actions: Dict[str, "__clapshot__.ActionDef"] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_MESSAGE
    )


@dataclass(eq=False, repr=False)
class ServerToClientCmdShowMessages(betterproto.Message):
    msgs: List["__clapshot__.UserMessage"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ServerToClientCmdOpenMediaFile(betterproto.Message):
    media_file: "__clapshot__.MediaFile" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ServerToClientCmdAddComments(betterproto.Message):
    comments: List["__clapshot__.Comment"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ServerToClientCmdDelComment(betterproto.Message):
    comment_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ServerToClientCmdCollabEvent(betterproto.Message):
    from_user: str = betterproto.string_field(1)
    paused: bool = betterproto.bool_field(2)
    loop: bool = betterproto.bool_field(3)
    seek_time_sec: float = betterproto.double_field(4)
    drawing: Optional[str] = betterproto.string_field(
        5, optional=True, group="_drawing"
    )
    subtitle_id: Optional[str] = betterproto.string_field(
        6, optional=True, group="_subtitle_id"
    )


@dataclass(eq=False, repr=False)
class ServerToClientCmdSetCookies(betterproto.Message):
    cookies: Dict[str, str] = betterproto.map_field(
        1, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    expire_time: datetime = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class ServerToClientCmdHemaParticipants(betterproto.Message):
    participants: List["__clapshot__.HemaParticipant"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ServerToClientCmdHemaMediaBouts(betterproto.Message):
    bouts: List["__clapshot__.HemaBout"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ClientToServerCmd(betterproto.Message):
    open_navigation_page: "ClientToServerCmdOpenNavigationPage" = (
        betterproto.message_field(10, group="cmd")
    )
    open_media_file: "ClientToServerCmdOpenMediaFile" = betterproto.message_field(
        20, group="cmd"
    )
    del_media_file: "ClientToServerCmdDelMediaFile" = betterproto.message_field(
        30, group="cmd"
    )
    rename_media_file: "ClientToServerCmdRenameMediaFile" = betterproto.message_field(
        40, group="cmd"
    )
    add_comment: "ClientToServerCmdAddComment" = betterproto.message_field(
        50, group="cmd"
    )
    edit_comment: "ClientToServerCmdEditComment" = betterproto.message_field(
        60, group="cmd"
    )
    del_comment: "ClientToServerCmdDelComment" = betterproto.message_field(
        70, group="cmd"
    )
    add_subtitle: "ClientToServerCmdAddSubtitle" = betterproto.message_field(
        75, group="cmd"
    )
    edit_subtitle_info: "ClientToServerCmdEditSubtitleInfo" = betterproto.message_field(
        76, group="cmd"
    )
    del_subtitle: "ClientToServerCmdDelSubtitle" = betterproto.message_field(
        77, group="cmd"
    )
    list_my_messages: "ClientToServerCmdListMyMessages" = betterproto.message_field(
        80, group="cmd"
    )
    join_collab: "ClientToServerCmdJoinCollab" = betterproto.message_field(
        90, group="cmd"
    )
    leave_collab: "ClientToServerCmdLeaveCollab" = betterproto.message_field(
        100, group="cmd"
    )
    collab_report: "ClientToServerCmdCollabReport" = betterproto.message_field(
        110, group="cmd"
    )
    organizer_cmd: "ClientToServerCmdOrganizerCmd" = betterproto.message_field(
        120, group="cmd"
    )
    move_to_folder: "ClientToServerCmdMoveToFolder" = betterproto.message_field(
        130, group="cmd"
    )
    reorder_items: "ClientToServerCmdReorderItems" = betterproto.message_field(
        140, group="cmd"
    )
    hema_add_participant: "ClientToServerCmdHemaAddParticipant" = (
        betterproto.message_field(160, group="cmd")
    )
    hema_set_media_participants: "ClientToServerCmdHemaSetMediaParticipants" = (
        betterproto.message_field(161, group="cmd")
    )
    hema_add_bout: "ClientToServerCmdHemaAddBout" = betterproto.message_field(
        162, group="cmd"
    )
    hema_update_bout: "ClientToServerCmdHemaUpdateBout" = betterproto.message_field(
        163, group="cmd"
    )
    hema_del_bout: "ClientToServerCmdHemaDelBout" = betterproto.message_field(
        164, group="cmd"
    )
    logout: "ClientToServerCmdLogout" = betterproto.message_field(150, group="cmd")


@dataclass(eq=False, repr=False)
class ClientToServerCmdOpenNavigationPage(betterproto.Message):
    page_id: Optional[str] = betterproto.string_field(
        1, optional=True, group="_page_id"
    )


@dataclass(eq=False, repr=False)
class ClientToServerCmdOpenMediaFile(betterproto.Message):
    media_file_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ClientToServerCmdDelMediaFile(betterproto.Message):
    media_file_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ClientToServerCmdRenameMediaFile(betterproto.Message):
    media_file_id: str = betterproto.string_field(1)
    new_name: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class ClientToServerCmdAddComment(betterproto.Message):
    media_file_id: str = betterproto.string_field(1)
    comment: str = betterproto.string_field(2)
    timecode: Optional[str] = betterproto.string_field(
        3, optional=True, group="_timecode"
    )
    parent_id: Optional[str] = betterproto.string_field(
        4, optional=True, group="_parent_id"
    )
    drawing: Optional[str] = betterproto.string_field(
        5, optional=True, group="_drawing"
    )
    subtitle_id: Optional[str] = betterproto.string_field(
        6, optional=True, group="_subtitle_id"
    )


@dataclass(eq=False, repr=False)
class ClientToServerCmdEditComment(betterproto.Message):
    comment_id: str = betterproto.string_field(1)
    new_comment: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class ClientToServerCmdDelComment(betterproto.Message):
    comment_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ClientToServerCmdAddSubtitle(betterproto.Message):
    media_file_id: str = betterproto.string_field(1)
    file_name: str = betterproto.string_field(2)
    contents_base64: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class ClientToServerCmdEditSubtitleInfo(betterproto.Message):
    id: str = betterproto.string_field(1)
    title: Optional[str] = betterproto.string_field(2, optional=True, group="_title")
    language_code: Optional[str] = betterproto.string_field(
        3, optional=True, group="_language_code"
    )
    time_offset: Optional[float] = betterproto.float_field(
        4, optional=True, group="_time_offset"
    )
    is_default: Optional[bool] = betterproto.bool_field(
        5, optional=True, group="_is_default"
    )


@dataclass(eq=False, repr=False)
class ClientToServerCmdDelSubtitle(betterproto.Message):
    id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ClientToServerCmdListMyMessages(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ClientToServerCmdJoinCollab(betterproto.Message):
    collab_id: str = betterproto.string_field(1)
    media_file_id: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class ClientToServerCmdLeaveCollab(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ClientToServerCmdCollabReport(betterproto.Message):
    paused: bool = betterproto.bool_field(1)
    loop: bool = betterproto.bool_field(2)
    seek_time_sec: float = betterproto.double_field(3)
    drawing: Optional[str] = betterproto.string_field(
        4, optional=True, group="_drawing"
    )
    subtitle_id: Optional[str] = betterproto.string_field(
        5, optional=True, group="_subtitle_id"
    )


@dataclass(eq=False, repr=False)
class ClientToServerCmdOrganizerCmd(betterproto.Message):
    cmd: str = betterproto.string_field(1)
    args: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class ClientToServerCmdMoveToFolder(betterproto.Message):
    dst_folder_id: str = betterproto.string_field(1)
    ids: List["__clapshot__.FolderItemId"] = betterproto.message_field(2)
    listing_data: Dict[str, str] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class ClientToServerCmdReorderItems(betterproto.Message):
    ids: List["__clapshot__.FolderItemId"] = betterproto.message_field(1)
    listing_data: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class ClientToServerCmdHemaAddParticipant(betterproto.Message):
    name: str = betterproto.string_field(1)
    club: Optional[str] = betterproto.string_field(2, optional=True, group="_club")


@dataclass(eq=False, repr=False)
class ClientToServerCmdHemaSetMediaParticipants(betterproto.Message):
    media_file_id: str = betterproto.string_field(1)
    participant_ids: List[int] = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class ClientToServerCmdHemaAddBout(betterproto.Message):
    bout: "__clapshot__.HemaBout" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ClientToServerCmdHemaUpdateBout(betterproto.Message):
    bout: "__clapshot__.HemaBout" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ClientToServerCmdHemaDelBout(betterproto.Message):
    bout_id: int = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class ClientToServerCmdLogout(betterproto.Message):
    pass
